name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install minimal stable with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-musl 
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - name: Build
      run: cd sps && cargo build --target=x86_64-unknown-linux-musl && cd ..
    - uses: actions/upload-artifact@v2
      with:
        name: sps-bleading-edge
        path: sps/target/x86_64-unknown-linux-musl/debug/sps
